# Generated by Django 3.2.9 on 2022-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220607_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='in_Rus',
            field=models.BooleanField(verbose_name='Факт нахождения в России'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(verbose_name='Факт зачисления'),
        ),
    ]
